services:
    avathar.bbguild_swtor.installer:
        class: avathar\bbguild_swtor\game\swtor_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguild_swtor.provider:
        class: avathar\bbguild_swtor\game\swtor_provider
        arguments:
            - '@avathar.bbguild_swtor.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
