services:
    avathar.bbguildswtor.installer:
        class: avathar\bbguildswtor\game\swtor_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildswtor.provider:
        class: avathar\bbguildswtor\game\swtor_provider
        arguments:
            - '@avathar.bbguildswtor.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
